# EmbedSpirv.cmake — convert compiled .spv files into a C array source.
# Usage:
#   cmake -DOUT_C=... -DOUT_H=... -DSPV_FILES="a.spv;b.spv" -P EmbedSpirv.cmake
#
# For each file named "foo.bar.spv" (or "foo_bar.spv"), emits:
#   const unsigned char foo_bar_spv[];
#   const size_t foo_bar_spv_len;

if(NOT OUT_C OR NOT OUT_H OR NOT SPV_FILES)
	message(FATAL_ERROR "EmbedSpirv.cmake requires OUT_C, OUT_H, SPV_FILES")
endif()

set(header_guard "SHADERS_EMBEDDED_H")
set(h_contents "/* Auto-generated by EmbedSpirv.cmake — do not edit. */\n#ifndef ${header_guard}\n#define ${header_guard}\n\n#include <stddef.h>\n\n")
set(c_contents "/* Auto-generated by EmbedSpirv.cmake — do not edit. */\n#include \"shaders_embedded.h\"\n\n")

foreach(spv ${SPV_FILES})
	get_filename_component(name_we "${spv}" NAME_WE)
	# ui.vert.spv → NAME_WE = ui.vert → ui_vert
	string(REPLACE "." "_" sym "${name_we}")

	file(READ "${spv}" hex_data HEX)
	string(LENGTH "${hex_data}" hex_len)
	math(EXPR byte_len "${hex_len} / 2")

	set(array_body "")
	set(i 0)
	while(i LESS hex_len)
		string(SUBSTRING "${hex_data}" ${i} 2 byte)
		string(APPEND array_body "0x${byte},")
		math(EXPR i "${i} + 2")
		math(EXPR n "${i} / 2")
		math(EXPR col "${n} % 12")
		if(col EQUAL 0)
			string(APPEND array_body "\n\t")
		endif()
	endwhile()

	string(APPEND h_contents "extern const unsigned char ${sym}_spv[];\n")
	string(APPEND h_contents "extern const size_t ${sym}_spv_len;\n\n")

	string(APPEND c_contents "const unsigned char ${sym}_spv[] = {\n\t${array_body}\n};\n")
	string(APPEND c_contents "const size_t ${sym}_spv_len = ${byte_len};\n\n")
endforeach()

string(APPEND h_contents "#endif /* ${header_guard} */\n")

file(WRITE "${OUT_H}" "${h_contents}")
file(WRITE "${OUT_C}" "${c_contents}")
